# Base configuration for content pipeline
# This file contains configurations for the automated content pipeline
# Secrets are stored separately in secrets.properties

# Default profile (base configuration)
default:
  # General settings
  cache_dir: "./cache"
  temp_dir: "./tmp"
  
  # Secrets configuration
  secrets_file: "secrets.properties"
  
  # LLM configuration
  llm_model: "gpt-4o"
  
  # B-roll detection settings
  broll_detection_strategy: "hybrid"  # Options: "rule_based", "llm_based", "hybrid"
  min_broll_separation: 4.0           # Minimum seconds between B-roll insertions
  max_broll_opportunities: 5          # Maximum number of B-roll opportunities to detect
  min_broll_duration: 1.5             # Minimum duration for B-roll (seconds)
  max_broll_duration: 4.0             # Maximum duration for B-roll (seconds)
  
  # Keyword extraction settings
  use_llm_for_keywords: true
  keyword_extraction_workers: 4
  
  # Video retrieval settings
  min_video_resolution: [1080, 1080]  # Minimum resolution (width, height)
  max_results_per_query: 5
  max_concurrent_requests: 3
  max_download_retries: 3
  
  # Video transformation settings
  target_video_width: 1080
  target_video_height: 1920
  
  # Pipeline execution settings
  retry_delay_base: 2                 # Base for exponential backoff (seconds)
  max_retries_per_step: 3             # Maximum retries per step

  # Post-processing configuration
  post_processing:
    # Enable/disable specific post-processing steps
    enabled: true
    steps:
      - sound_effects
      - background_music
      # Uncomment these as needed
      - camera_movements
      - transitions
      - captioning
  
    # Sound effects configuration
    sound_effects:
      sound_effects_dir: "./assets/sound_effects"
      volume: 0.7                     # Global volume scale (0.1-1.0)
      enable_transitions: true        # Enable transition sound effects
      enable_ambient: true            # Enable ambient sound effects
      randomize_selection: true       # Randomize sound effect selection
      max_sounds_per_video: 5         # Maximum number of sound effects per video
      min_gap: 3.0                    # Minimum gap between sound effects (seconds)
  
    # Background music configuration
    background_music:
        enabled: true                     # Whether to enable background music
        music_dir: "./assets/background_music"  # Directory containing background music files
        volume: 0.15                      # Base volume for background music (0.0-1.0)
        ducking: 0.5                      # Ducking amount for dialog (0.0-1.0) 
        smart_ducking: true               # Use smart ducking based on audio analysis
        fade_in: 2.0                      # Fade-in duration (seconds)
        fade_out: 3.0                     # Fade-out duration (seconds)
  
    # Camera movements configuration (zoom, shake, punch-in)
    camera_movements:
      enabled: true                  # Enable camera movement effects
      zoom_factor: 1.1                # Maximum zoom factor for slow zoom
      shake_intensity: 2.0            # Maximum pixel displacement for camera shake
      punchin_factor: 1.08            # Maximum zoom factor for punch-in effect
      frame_rate: 30                  # Frame rate for the output video
      zoom_duration: 100              # Number of frames for the zoom-in effect
      shake_duration: 60              # Number of frames for the camera shake effect
      punchin_duration: 50            # Number of frames for the punch-in effect
      normal_duration: 40             # Number of frames between effects
      shake_interval: 450             # Minimum frames between shake effects
  
    # Video transitions configuration
    transitions:
      enabled: true                  # Enable transition effects
      type: "cross_fade"              # Default transition type
      duration: 20                    # Transition duration in frames
      randomize: true                # Randomize transition types
      transitions_file: "./transitions.json"  # Path to transitions configuration file
      max_transitions: 5              # Maximum number of transitions to insert
  
    # Captioning configuration
    captioning:
      enabled: true                  # Enable captioning
      api_url: "https://ai-content-pipeline.onrender.com/caption-video"
      # font_size: 16                   # Font size for captions
      # position: "bottom"              # Caption position (top, bottom, middle)

# Development profile
development:
  cache_dir: "./dev_cache"
  max_broll_opportunities: 2          # Reduced for faster development testing
  use_llm_for_keywords: false         # Use rule-based approach for faster development
  max_results_per_query: 2
  post_processing:
    enabled: true
    steps:
      - sound_effects
    sound_effects:
      volume: 0.7

# Production profile
production:
  cache_dir: "/data/pipeline_cache"
  max_retries_per_step: 5             # More retries for production reliability
  max_broll_opportunities: 8          # More opportunities for production quality
  retry_delay_base: 5                 # Longer backoff time for production stability
  post_processing:
    enabled: true
    steps:
      - sound_effects
      - background_music
      - camera_movements
      - transitions
      - captioning
    # Use default configuration for all other settings

# High-quality profile
high_quality:
  llm_model: "gpt-4o"                 # Use most capable model
  broll_detection_strategy: "llm_based"
  max_broll_opportunities: 10
  max_results_per_query: 8
  target_video_width: 1080
  target_video_height: 1920
  post_processing:
    enabled: true
    steps:
      - sound_effects
      - background_music
      - camera_movements
      - transitions
      - captioning
    sound_effects:
      volume: 0.8
      max_sounds_per_video: 7
    background_music:
      volume: 0.12
      smart_ducking: true
    camera_movements:
      zoom_factor: 1.05               # More subtle zoom for higher quality
      shake_intensity: 1.5            # More subtle shake for higher quality
    transitions:
      randomize: true                 # Use random transitions for variety

# Fast processing profile
fast:
  broll_detection_strategy: "rule_based"
  use_llm_for_keywords: false
  max_broll_opportunities: 3
  max_results_per_query: 3
  parallel_execution: true
  post_processing:
    enabled: true
    steps:
      - sound_effects
    # Minimal post-processing for fast results