# Base configuration for content pipeline
# This file contains configurations for the automated content pipeline
# Secrets are stored separately in secrets.properties

# Default profile (base configuration)
default:
  # General settings
  cache_dir: "./cache"
  temp_dir: "./tmp"
  
  # Secrets configuration
  secrets_file: "secrets.properties"
  
  # LLM configuration
  llm_model: "gpt-4o"
  
  # B-roll detection settings
  broll_detection_strategy: "hybrid"  # Options: "rule_based", "llm_based", "hybrid"
  min_broll_separation: 4.0           # Minimum seconds between B-roll insertions
  max_broll_opportunities: 5          # Maximum number of B-roll opportunities to detect
  min_broll_duration: 1.5             # Minimum duration for B-roll (seconds)
  max_broll_duration: 4.0             # Maximum duration for B-roll (seconds)
  
  # Keyword extraction settings
  use_llm_for_keywords: true
  keyword_extraction_workers: 4
  
  # Video retrieval settings
  min_video_resolution: [1080, 1080]  # Minimum resolution (width, height)
  max_results_per_query: 5
  max_concurrent_requests: 3
  max_download_retries: 3
  
  # Video transformation settings
  target_video_width: 1080
  target_video_height: 1920
  
  # Pipeline execution settings
  retry_delay_base: 2                 # Base for exponential backoff (seconds)
  max_retries_per_step: 3             # Maximum retries per step

# Development profile
development:
  cache_dir: "./dev_cache"
  max_broll_opportunities: 2          # Reduced for faster development testing
  use_llm_for_keywords: false         # Use rule-based approach for faster development
  max_results_per_query: 2

# Production profile
production:
  cache_dir: "/data/pipeline_cache"
  max_retries_per_step: 5             # More retries for production reliability
  max_broll_opportunities: 8          # More opportunities for production quality
  retry_delay_base: 5                 # Longer backoff time for production stability

# High-quality profile
high_quality:
  llm_model: "gpt-4o"                 # Use most capable model
  broll_detection_strategy: "llm_based"
  max_broll_opportunities: 10
  max_results_per_query: 8
  target_video_width: 1080
  target_video_height: 1920

# Fast processing profile
fast:
  broll_detection_strategy: "rule_based"
  use_llm_for_keywords: false
  max_broll_opportunities: 3
  max_results_per_query: 3
  parallel_execution: true

  post_processing:
  # Enable/disable specific post-processing steps
  enabled: true
  steps:
    - sound_effects
    # Uncomment these as they are implemented
    # - video_transitions
    # - zoom_effects
    # - captioning
  
  # Sound effects configuration
  sound_effects:
    sound_effects_dir: "./assets/sound_effects"
    fade_duration: 0.3
    volume: 0.7
    max_sounds_per_video: 5
    min_gap: 3.0
  
  # Video transitions configuration (placeholder for future implementation)
  video_transitions:
    enabled: false
    transition_types:
      - fade
      - wipe
      - dissolve
    default_duration: 0.5
  
  # Zoom effects configuration (placeholder for future implementation)
  zoom_effects:
    enabled: false
    zoom_intensity: 1.2
    zoom_duration: 1.5
    
  # Captioning configuration (placeholder for future implementation)
  captioning:
    enabled: false
    api_url: ""
    api_key: ""
    font_size: 16
    position: "bottom"

  # Background music configuration
  background_music:
    enabled: true
    music_dir: "./assets/background_music"
    volume: 0.15
    ducking: 0.5
    smart_ducking: true
    fade_in: 2.0
    fade_out: 3.0